// ==========================================
// FAR-POS - Multi-Industry Point of Sale
// Configuration file
// ==========================================

export const INDUSTRIES = {
  kirana: {
    id: 'kirana',
    name: 'Kirana / General Store',
    icon: '🏪',
    description: 'Grocery, daily essentials, inventory management',
    color: '#0D9488',
    features: ['billing', 'inventory', 'khata', 'reports'],
    tabs: ['billing', 'inventory', 'khata', 'reports'],
    defaultCategories: ['Grocery', 'FMCG', 'Snacks', 'Dairy', 'Beverages', 'Other'],
    productFields: ['name', 'price', 'stock', 'unit', 'category', 'gst'],
    sampleProducts: [
      { id: 'p1', name: 'Toor Dal', price: 140, stock: 25, unit: 'kg', category: 'Grocery', gst: 5 },
      { id: 'p2', name: 'Basmati Rice', price: 95, stock: 50, unit: 'kg', category: 'Grocery', gst: 5 },
      { id: 'p3', name: 'Sunflower Oil', price: 180, stock: 12, unit: 'L', category: 'Grocery', gst: 5 },
      { id: 'p4', name: 'Sugar', price: 45, stock: 40, unit: 'kg', category: 'Grocery', gst: 5 },
    ],
  },
  restaurant: {
    id: 'restaurant',
    name: 'Restaurant / Cafe',
    icon: '🍽️',
    description: 'Dine-in, takeout, table management, orders',
    color: '#E85D25',
    features: ['billing', 'orders', 'tables', 'khata', 'reports'],
    tabs: ['billing', 'orders', 'tables', 'khata', 'reports'],
    defaultCategories: ['Starters', 'Main Course', 'Desserts', 'Beverages', 'Snacks'],
    productFields: ['name', 'price', 'category', 'prep_time'],
    sampleProducts: [
      { id: 'p1', name: 'Butter Chicken', price: 350, category: 'Main Course', prep_time: 20 },
      { id: 'p2', name: 'Samosa', price: 30, category: 'Snacks', prep_time: 5 },
      { id: 'p3', name: 'Biryani', price: 250, category: 'Main Course', prep_time: 25 },
    ],
  },
  cloth: {
    id: 'cloth',
    name: 'Clothing Boutique',
    icon: '👕',
    description: 'Size/color variants, fitting rooms, inventory by size',
    color: '#9333EA',
    features: ['billing', 'inventory', 'variants', 'khata', 'reports'],
    tabs: ['billing', 'inventory', 'variants', 'khata', 'reports'],
    defaultCategories: ['Men', 'Women', 'Kids', 'Accessories'],
    productFields: ['name', 'price', 'category', 'sizes', 'colors'],
    sampleProducts: [
      { id: 'p1', name: 'Cotton T-Shirt', price: 399, category: 'Men', sizes: ['S', 'M', 'L', 'XL'], colors: ['Blue', 'Red', 'Black'] },
      { id: 'p2', name: 'Jeans', price: 999, category: 'Men', sizes: ['28', '30', '32', '34', '36'], colors: ['Blue', 'Black'] },
    ],
  },
  tiffin: {
    id: 'tiffin',
    name: 'Tiffin / Food Service',
    icon: '🍱',
    description: 'Meal plans, subscriptions, delivery tracking',
    color: '#D97706',
    features: ['billing', 'subscriptions', 'delivery', 'khata', 'reports'],
    tabs: ['billing', 'subscriptions', 'delivery', 'khata', 'reports'],
    defaultCategories: ['Breakfast', 'Lunch', 'Dinner', 'Snacks', 'Combos'],
    productFields: ['name', 'price', 'serving_size', 'daily_quota'],
    sampleProducts: [
      { id: 'p1', name: 'Lunch Meal', price: 200, serving_size: '2 person', daily_quota: 50 },
      { id: 'p2', name: 'Breakfast', price: 120, serving_size: '1 person', daily_quota: 30 },
      { id: 'p3', name: 'Dinner Combo', price: 250, serving_size: '2 person', daily_quota: 40 },
    ],
  },
  pharmacy: {
    id: 'pharmacy',
    name: 'Pharmacy',
    icon: '💊',
    description: 'Medicine inventory, batch/expiry tracking, prescriptions',
    color: '#059669',
    features: ['billing', 'inventory', 'khata', 'reports'],
    tabs: ['billing', 'inventory', 'khata', 'reports'],
    defaultCategories: ['Tablets', 'Capsules', 'Syrups', 'Ointments', 'Supplements'],
    productFields: ['name', 'price', 'batch_number', 'expiry_date', 'stock'],
    sampleProducts: [
      { id: 'p1', name: 'Aspirin 500mg', price: 20, batch: 'BATCH001', expiry: '2026-12-31', stock: 100 },
      { id: 'p2', name: 'Cough Syrup', price: 150, batch: 'BATCH002', expiry: '2026-10-15', stock: 25 },
    ],
  },
  salon: {
    id: 'salon',
    name: 'Salon / Spa',
    icon: '💇',
    description: 'Service booking, staff management, appointments',
    color: '#DC2626',
    features: ['billing', 'appointments', 'staff', 'khata', 'reports'],
    tabs: ['billing', 'appointments', 'staff', 'khata', 'reports'],
    defaultCategories: ['Hair', 'Skin', 'Nails', 'Packages'],
    productFields: ['name', 'price', 'duration_minutes', 'staff_required'],
    sampleProducts: [
      { id: 'p1', name: 'Haircut', price: 300, duration: 30, staff: 'Barber' },
      { id: 'p2', name: 'Facial', price: 500, duration: 60, staff: 'Therapist' },
      { id: 'p3', name: 'Massage', price: 800, duration: 90, staff: 'Therapist' },
    ],
  },
toys: {
    id: 'toys',
    name: 'Toy Store',
    icon: '🧸',
    description: 'Toys, games, educational playthings, age-appropriate inventory',
    color: '#EC4899',
    features: ['billing', 'inventory', 'khata', 'reports'],
    tabs: ['billing', 'inventory', 'khata', 'reports'],
    defaultCategories: ['Action Figures', 'Building Blocks', 'Dolls & Plushies', 'Educational', 'Outdoor', 'Board Games', 'Vehicles', 'Arts & Crafts'],
    productFields: ['name', 'price', 'stock', 'category', 'age_group', 'gst'],
    sampleProducts: [
      { id: 'p1', name: 'Marvel Superhero Action Figure', price: 399, stock: 15, category: 'Action Figures', age_group: '4+', gst: 12 },
      { id: 'p2', name: 'DC Comics Batman Figure', price: 349, stock: 12, category: 'Action Figures', age_group: '5+', gst: 12 },
      { id: 'p3', name: 'Dinosaur Action Figure Set (12 pcs)', price: 499, stock: 8, category: 'Action Figures', age_group: '3+', gst: 12 },
      { id: 'p4', name: 'Robot Transformer Toy', price: 599, stock: 6, category: 'Action Figures', age_group: '6+', gst: 12 },
      { id: 'p5', name: 'LEGO Classic Bricks Set (500 pcs)', price: 1299, stock: 10, category: 'Building Blocks', age_group: '4+', gst: 12 },
      { id: 'p6', name: 'LEGO Star Wars Building Set', price: 2499, stock: 5, category: 'Building Blocks', age_group: '8+', gst: 12 },
      { id: 'p7', name: 'Wooden Building Blocks Set (100 pcs)', price: 699, stock: 12, category: 'Building Blocks', age_group: '2+', gst: 12 },
      { id: 'p8', name: 'Magnetic Building Blocks (50 pcs)', price: 899, stock: 8, category: 'Building Blocks', age_group: '3+', gst: 12 },
      { id: 'p9', name: 'Construction Block Set', price: 1099, stock: 7, category: 'Building Blocks', age_group: '5+', gst: 12 },
      { id: 'p10', name: 'Barbie Fashion Doll', price: 649, stock: 10, category: 'Dolls & Plushies', age_group: '3+', gst: 12 },
      { id: 'p11', name: 'Baby Doll with Accessories', price: 499, stock: 12, category: 'Dolls & Plushies', age_group: '2+', gst: 12 },
      { id: 'p12', name: 'Plush Teddy Bear (24 inch)', price: 399, stock: 15, category: 'Dolls & Plushies', age_group: '1+', gst: 12 },
      { id: 'p13', name: 'Cute Animal Plushies Set (6 pcs)', price: 599, stock: 8, category: 'Dolls & Plushies', age_group: '2+', gst: 12 },
      { id: 'p14', name: 'Disney Princess Doll', price: 749, stock: 6, category: 'Dolls & Plushies', age_group: '4+', gst: 12 },
      { id: 'p15', name: 'Puzzle Games (100 pieces)', price: 299, stock: 18, category: 'Educational', age_group: '3+', gst: 12 },
      { id: 'p16', name: 'Learning Alphabets Flashcard Set', price: 199, stock: 20, category: 'Educational', age_group: '2+', gst: 12 },
      { id: 'p17', name: 'Math Learning Toy (1-100 Numbers)', price: 449, stock: 10, category: 'Educational', age_group: '3+', gst: 12 },
      { id: 'p18', name: 'Shape & Color Sorting Toy', price: 349, stock: 14, category: 'Educational', age_group: '1+', gst: 12 },
      { id: 'p19', name: 'Memory Card Game Set', price: 249, stock: 16, category: 'Educational', age_group: '4+', gst: 12 },
      { id: 'p20', name: 'Globe & World Map Learning Kit', price: 599, stock: 7, category: 'Educational', age_group: '5+', gst: 12 },
      { id: 'p21', name: 'Microscope Beginner Kit', price: 899, stock: 5, category: 'Educational', age_group: '8+', gst: 12 },
      { id: 'p22', name: 'Bicycle (20 inch)', price: 3499, stock: 3, category: 'Outdoor', age_group: '6+', gst: 12 },
      { id: 'p23', name: 'Roller Skates (Adjustable Size)', price: 1299, stock: 5, category: 'Outdoor', age_group: '5+', gst: 12 },
      { id: 'p24', name: 'Skateboard (Complete)', price: 1899, stock: 4, category: 'Outdoor', age_group: '8+', gst: 12 },
      { id: 'p25', name: 'Cricket Set (Bat, Ball, Stumps)', price: 799, stock: 10, category: 'Outdoor', age_group: '5+', gst: 12 },
      { id: 'p26', name: 'Badminton Racket Set', price: 599, stock: 12, category: 'Outdoor', age_group: '4+', gst: 12 },
      { id: 'p27', name: 'Kite Flying Set', price: 199, stock: 25, category: 'Outdoor', age_group: '3+', gst: 12 },
      { id: 'p28', name: 'Frisbee', price: 149, stock: 30, category: 'Outdoor', age_group: '3+', gst: 12 },
      { id: 'p29', name: 'Jump Rope', price: 99, stock: 40, category: 'Outdoor', age_group: '3+', gst: 12 },
      { id: 'p30', name: 'Ludo Game Board', price: 249, stock: 18, category: 'Board Games', age_group: '4+', gst: 12 },
      { id: 'p31', name: 'Snakes & Ladders Game', price: 199, stock: 20, category: 'Board Games', age_group: '3+', gst: 12 },
      { id: 'p32', name: 'Chess Set (Wooden)', price: 699, stock: 8, category: 'Board Games', age_group: '6+', gst: 12 },
      { id: 'p33', name: 'Carrom Board', price: 1299, stock: 4, category: 'Board Games', age_group: '5+', gst: 12 },
      { id: 'p34', name: 'Playing Cards Set', price: 99, stock: 50, category: 'Board Games', age_group: '4+', gst: 12 },
      { id: 'p35', name: 'Monopoly Game', price: 899, stock: 6, category: 'Board Games', age_group: '8+', gst: 12 },
      { id: 'p36', name: 'Toy Cars Set (Die-cast, 12 pcs)', price: 599, stock: 12, category: 'Vehicles', age_group: '3+', gst: 12 },
      { id: 'p37', name: 'Remote Control Car', price: 1199, stock: 6, category: 'Vehicles', age_group: '6+', gst: 12 },
      { id: 'p38', name: 'Train Set with Tracks', price: 1499, stock: 5, category: 'Vehicles', age_group: '4+', gst: 12 },
      { id: 'p39', name: 'Helicopter Toy (Wind-up)', price: 299, stock: 16, category: 'Vehicles', age_group: '4+', gst: 12 },
      { id: 'p40', name: 'Airplane Model Set', price: 449, stock: 10, category: 'Vehicles', age_group: '5+', gst: 12 },
      { id: 'p41', name: 'Truck & Trailer Set', price: 699, stock: 8, category: 'Vehicles', age_group: '3+', gst: 12 },
      { id: 'p42', name: 'Color Pencil Set (36 colors)', price: 299, stock: 20, category: 'Arts & Crafts', age_group: '3+', gst: 12 },
      { id: 'p43', name: 'Watercolor Paint Set', price: 249, stock: 18, category: 'Arts & Crafts', age_group: '4+', gst: 12 },
      { id: 'p44', name: 'Sketch Pad (A4, 100 sheets)', price: 199, stock: 25, category: 'Arts & Crafts', age_group: '3+', gst: 12 },
      { id: 'p45', name: 'Clay Modeling Set (6 colors)', price: 149, stock: 30, category: 'Arts & Crafts', age_group: '2+', gst: 12 },
      { id: 'p46', name: 'Beads & String Craft Kit', price: 399, stock: 12, category: 'Arts & Crafts', age_group: '5+', gst: 12 },
      { id: 'p47', name: 'Sticker Art Set', price: 199, stock: 24, category: 'Arts & Crafts', age_group: '2+', gst: 12 },
      { id: 'p48', name: 'Origami Paper Set', price: 149, stock: 28, category: 'Arts & Crafts', age_group: '4+', gst: 12 },
    ],
  },
};

export const TRANSLATIONS = {
  en: {
    welcome: 'Welcome to FAR-POS',
    selectIndustry: 'What type of business are you running?',
    startUsing: 'Start Using FAR-POS',
    setupShop: 'Setup Your Shop',
    billing: 'Billing',
    inventory: 'Inventory',
    khata: 'Khata',
    orders: 'Orders',
    tables: 'Tables',
    subscriptions: 'Subscriptions',
    staff: 'Staff',
    variants: 'Variants',
    appointments: 'Appointments',
    delivery: 'Delivery',
    reports: 'Reports',
    settings: 'Settings',
    search: 'Search products or scan barcode...',
    cart: 'Current Bill',
    qty: 'Qty',
    price: 'Price',
    amount: 'Amount',
    product: 'Product',
    unit: 'Unit',
    category: 'Category',
    addToCart: 'Add',
    removeItem: 'Remove',
    clearCart: 'Clear Cart',
    subtotal: 'Subtotal',
    gst: 'GST',
    discount: 'Discount',
    grandTotal: 'Grand Total',
    total: 'Total',
    pay: 'Cash / UPI',
    credit: 'Khata',
    printBill: 'Print Bill',
    stock: 'Stock',
    lowStockAlerts: 'Low Stock Alerts',
    addProduct: 'Add Product',
    editProduct: 'Edit Product',
    deleteProduct: 'Delete',
    productName: 'Product Name',
    sellingPrice: 'Selling Price',
    costPrice: 'Cost Price',
    stockQty: 'Stock Quantity',
    lowStockAt: 'Low Stock Alert At',
    save: 'Save',
    cancel: 'Cancel',
    customer: 'Customer',
    phone: 'Phone',
    balance: 'Credit Balance',
    lastVisit: 'Last Visit',
    totalOutstanding: 'Total Outstanding Credit',
    customersWithCredit: 'customers with pending credit',
    noPending: 'No pending credit',
    recordPayment: 'Record Payment',
    markPaid: 'Mark as Paid',
    enterAmount: 'Enter amount',
    paymentRecorded: 'Payment Recorded!',
    sendReminder: 'Send WhatsApp Reminder',
    addCustomer: 'Add Customer',
    dailySummary: "Today's Summary",
    totalSales: 'Total Sales',
    totalBills: 'Bills',
    cashCollected: 'Cash Collected',
    creditGiven: 'Credit Given',
    profit: 'Est. Profit',
    topProducts: 'Top Selling Products',
    billHistory: 'Recent Bills',
    shopName: 'Shop Name',
    ownerName: 'Owner Name',
    address: 'Address',
    gstNumber: 'GST Number',
    language: 'Language',
    changeIndustry: 'Change Business Type',
    getStarted: 'Get Started',
    selectLanguage: 'Select Language',
    logout: 'Logout',
    back: 'Back',
    next: 'Next',
    submit: 'Submit',
    update: 'Update',
    close: 'Close',
    savedSuccess: 'Saved!',
    paymentSuccess: 'Payment Successful!',
    khataSuccess: 'Added to Khata!',
    errorOccurred: 'Error occurred. Please try again.',
    noProducts: 'No products found',
    noData: 'No data yet. Start billing!',
  },
  hi: {
    welcome: 'FAR-POS में आपका स्वागत है',
    billing: 'बिलिंग',
    inventory: 'इन्वेंटरी',
    khata: 'खाता',
    products: 'उत्पाद',
    history: 'इतिहास',
    reports: 'रिपोर्ट',
    settings: 'सेटिंग्स',
    cart: 'वर्तमान बिल',
    subtotal: 'उप-कुल',
    gst: 'जीएसटी',
    discount: 'छूट',
    total: 'कुल',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    customer: 'ग्राहक',
    phone: 'फोन',
    totalSales: 'कुल बिक्री',
    netProfit: 'शुद्ध लाभ',
    logout: 'लॉग आउट',
    back: 'वापस',
    next: 'आगे',
    addProduct: 'उत्पाद जोड़ें',
    stock: 'स्टॉक',
    markPaid: 'भुगतान हो गया',
    daily: 'दैनिक',
    weekly: 'साप्ताहिक',
    monthly: 'मासिक',
    expense: 'खर्च',
    address: 'पता',
    paid: 'भुगतान हो गया',
  },
  te: {
    welcome: 'FAR-POS కి స్వాగతం',
    selectIndustry: 'మీరు ఏ రకమైన వ్యాపారం చేస్తున్నారు?',
    startUsing: 'FAR-POS ఉపయోగించటం ప్రారంభించండి',
    setupShop: 'మీ దుకాణం సెటప్ చేయండి',
    billing: 'బిల్లింగ్',
    inventory: 'ఇన్వెంటరీ',
    khata: 'ఖాతా',
    orders: 'ఆర్డర్లు',
    tables: 'టేబుల్‌లు',
    subscriptions: 'సబ్‌స్క్రిప్షన్‌లు',
    reports: 'రిపోర్టులు',
    search: 'ఉత్పత్తులు వెతకండి...',
    cart: 'ప్రస్తుత బిల్లు',
    qty: 'పరిమాణం',
    price: 'ధర',
    product: 'ఉత్పత్తి',
    unit: 'యూనిట్',
    category: 'వర్గం',
    subtotal: 'సబ్‌టోటల్',
    gst: 'జిఎస్టీ',
    grandTotal: 'గ్రాండ్ టోటల్',
    total: 'మొత్తం',
    pay: 'నగదు / UPI',
    credit: 'ఖాతా',
    customer: 'కస్టమర్',
    phone: 'ఫోన్',
    balance: 'అరువు బ్యాలన్స్',
    recordPayment: 'చెల్లింపు నమోదు చేయండి',
    totalSales: 'మొత్తం అమ్మకాలు',
    totalBills: 'బిల్లులు',
    cashCollected: 'నగదు సేకరించారు',
    creditGiven: 'ఖాతా ఇచ్చారు',
    shopName: 'దుకాణం పేరు',
    ownerName: 'యజమాని పేరు',
    address: 'చిరునామా',
    language: 'భాష',
    getStarted: 'ప్రారంభించండి',
    save: 'సేవ్',
    cancel: 'రద్దు',
    submit: 'సమర్పించండు',
  },
};

export const DEFAULT_SETTINGS = {
  currency: 'INR',
  timezone: 'Asia/Kolkata',
  dateFormat: 'DD/MM/YYYY',
  language: 'en',
  gstEnabled: true,
  defaultGstRate: 5,
  billPrefix: 'BILL',
  printReceipt: true,
};

export const PAYMENT_MODES = ['cash', 'upi', 'card', 'credit', 'cheque'];
export const ORDER_STATUSES = ['pending', 'preparing', 'ready', 'served', 'cancelled'];
export const SUBSCRIPTION_TYPES = ['5-day', '10-day', 'monthly', 'custom'];
export const STAFF_ROLES = ['owner', 'manager', 'cashier', 'chef', 'waiter', 'delivery', 'therapist'];
